obj-$(CONFIG_SHSYS_CUST)	+= shsys/
obj-$(CONFIG_SHDIAG)		+= shdiag/
obj-$(CONFIG_SENSORS_PROXIMITY) += proximity/
obj-$(CONFIG_SHBOOT_CUST)	+= shboot/
obj-$(CONFIG_SHUB)		+= shsensor_hub/ml630q790/
obj-$(CONFIG_SHIRDA)		+= shirda/
obj-$(CONFIG_NFC_T6NE6)		+= nfc/T6NE6/
obj-$(CONFIG_SHDISP)		+= shdisp/
